### ISSUE TITLE
[PR proposal] HTTP API for config generation

### ISSUE THREAD

**Issue by n-epifanov** [prometheus/snmp_exporter#1046]
Hi, thanks for the app!
Here's a feature I could provide PR for.
Generator README states a problem of MIBs conflicting with each other and advises to keep them separate. I'd like to propose a feature allowing to ease the pain.
An app could handle a POST request with a directory path, that directory would contain a minimal amount of MIBs required for producing a piece of snmp.yml. That snmp.yml would be returned for a POST request.
That would allow to generate snmp.yml pieces which could be later combined into a single config, right as it is recommended in generator README.
Initially I went with reusing generator features in a `snmp_exporter` app to have a single web-service, which could generate configs as well, but probably it would make more sense to add a web-service feature to a generator which could be enabled with a command-line parameter?
What do you think about this feature? Could it be useful for this project? Do you have any suggestions on how this feature could be implemented in a better way to suit this project application?

**Comment by SuperQ** [comment]
An API isn't going to help the fundamental functionality. It will still the be same if you call it via CLI or via API. The main reason the generator is separate from the exporter itself is that it requires being built against net-snmp with CGO. We want to ship a static binary without CGO for the exporter in order to make sure it's OS agnostic. If we combined them it would require installing net-snmp, which would differ between systems like Debian or RedHat. This would make it a lot harder to support.

We've already made a few improvements that solve a lot of the conflict issues.
* The exporter itself now accepts multiple config files.
* You can now call the generator with different MIBDIRs and generator filenames and output filenames.
* The auth and modules are now split so you don't need to generate a module per community/v3 auth.

The one feature I would like to implement is to allow the MIBDIRs path list to be part of the generator module config, this way you can separate the conflicting MIBs from each other in a single generator config.

**Comment by n-epifanov** [comment]
Thanks, I totally get your point and I agree with that. Another problem though is integrating `snmp_exporter` with other web-services, it's ok as long as config is static, but once it needs to be updated automatically it gets cumbersome. Is it that config is supposed to be generated once in a while manually?

**Comment by SuperQ** [comment]
There are hundreds of tools for configuration management and continuous integration/delivery. An API won't help with that.

**Comment by n-epifanov** [comment]
There's no point in using `snmp_exporter` for config management indeed. But there's a need for generating configs generator.yml + MIBs => snmp.yml which those tools don't cover.

**Comment by SuperQ** [comment]
That is what CI/CD pipelines are for. For example exactly how we run the generator tests with CircleCI here. And again, an API would not help with this.
