### ISSUE TITLE
No debug log, info via HTTP, or metric on internal parsing error

### ISSUE THREAD

**Issue by moepman** [prometheus/snmp_exporter#146]
I am running snmp_exporter with the example config only amended in the default module by the following:
```YAML
  version: 2
  auth:
    community: SomeCommunityString
```

Testing a switch via wget results in an internal server error:

> $ wget http://127.0.0.1:9116/snmp?target=switch1
--2017-04-21 08:42:25--  http://127.0.0.1:9116/snmp?target=switch1
Connecting to 127.0.0.1:9116... connected.
HTTP request sent, awaiting response...
500 Internal Server Error
2017-04-21 08:42:29 ERROR 500: Internal Server Error.

While the debug log from snmp_exporter gives no useful information on what went wrong:

> ./snmp_exporter -log.level=debug
INFO[0000] Starting snmp exporter (version=0.3.0, branch=master, revision=6f8aa8a24d720b36991f29ffb179b2896e92090b)  source=main.go:99
INFO[0000] Build context (go=go1.7.5, user=root@07f1e81a0104, date=20170315-16:01:54)  source=main.go:100
INFO[0000] Listening on :9116                            source=main.go:114
DEBU[0009] Scraping target 'switch1' with module 'default'  source=main.go:77
DEBU[0009] Walking target "switch1" subtree "1.3.6.1.2.1.1.3"  source=collector.go:71
DEBU[0009] Walk of target "switch1" subtree "1.3.6.1.2.1.1.3" completed in 75.952882ms  source=collector.go:81
DEBU[0009] Walking target "switch1" subtree "1.3.6.1.2.1.2"  source=collector.go:71
DEBU[0013] Walk of target "switch1" subtree "1.3.6.1.2.1.2" completed in 3.508447929s  source=collector.go:81
DEBU[0013] Walking target "switch1" subtree "1.3.6.1.2.1.31.1.1"  source=collector.go:71
DEBU[0014] Walk of target "switch1" subtree "1.3.6.1.2.1.31.1.1" completed in 964.529721ms  source=collector.go:81
DEBU[0014] Scrape of target 'switch1' with module 'default' took 4.660900 seconds  source=main.go:88

**Comment by RichiH** [comment]
Which switch model and software version, specifically?

**Comment by RichiH** [comment]
Also, what does /metrics say after that scrape attempt?

**Comment by RichiH** [comment]
Finally, can you paste the output of manual snmpbulkget on those three OIDs?

**Comment by SuperQ** [comment]
It would be worth trying each walk OID separately, one at a time, by commenting out the others in snmp.yml.  This may help determine which one is the cause of the bug.

**Comment by moepman** [comment]
The switch is an HP ProCurve 5406zl, running version K.15.16.0016m.

Metrics:
````
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.00025062
go_gc_duration_seconds{quantile="0.25"} 0.000284275
go_gc_duration_seconds{quantile="0.5"} 0.000327091
go_gc_duration_seconds{quantile="0.75"} 0.00036786
go_gc_duration_seconds{quantile="1"} 0.00041210400000000005
go_gc_duration_seconds_sum 0.002571663
go_gc_duration_seconds_count 8
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 5
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 5.102176e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 2.2274568e+07
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.44635e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 357304
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 471040
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 5.102176e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 884736
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 5.865472e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 69401
# HELP go_memstats_heap_released_bytes_total Total number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes_total counter
go_memstats_heap_released_bytes_total 0
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 6.750208e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.4927587766137261e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 27
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 426705
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 9600
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 92960
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 114688
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 6.162973e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 2.250538e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 589824
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 589824
# HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.1639032e+07
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.25
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 9.351168e+06
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.4927587739e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.8423808e+07
# HELP snmp_collection_duration_seconds Duration of collections by the SNMP exporter
# TYPE snmp_collection_duration_seconds summary
snmp_collection_duration_seconds{module="apcups",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="apcups",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="apcups",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="apcups"} 0
snmp_collection_duration_seconds_count{module="apcups"} 0
snmp_collection_duration_seconds{module="arista_sw",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="arista_sw",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="arista_sw",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="arista_sw"} 0
snmp_collection_duration_seconds_count{module="arista_sw"} 0
snmp_collection_duration_seconds{module="cisco_wlc",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="cisco_wlc",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="cisco_wlc",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="cisco_wlc"} 0
snmp_collection_duration_seconds_count{module="cisco_wlc"} 0
snmp_collection_duration_seconds{module="default",quantile="0.5"} 0.955964451
snmp_collection_duration_seconds{module="default",quantile="0.9"} 0.955964451
snmp_collection_duration_seconds{module="default",quantile="0.99"} 0.955964451
snmp_collection_duration_seconds_sum{module="default"} 0.955964451
snmp_collection_duration_seconds_count{module="default"} 1
snmp_collection_duration_seconds{module="default_ifindex",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="default_ifindex",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="default_ifindex",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="default_ifindex"} 0
snmp_collection_duration_seconds_count{module="default_ifindex"} 0
snmp_collection_duration_seconds{module="default_ifname",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="default_ifname",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="default_ifname",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="default_ifname"} 0
snmp_collection_duration_seconds_count{module="default_ifname"} 0
snmp_collection_duration_seconds{module="fortinet_fortigate",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="fortinet_fortigate",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="fortinet_fortigate",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="fortinet_fortigate"} 0
snmp_collection_duration_seconds_count{module="fortinet_fortigate"} 0
snmp_collection_duration_seconds{module="paloalto_fw",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="paloalto_fw",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="paloalto_fw",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="paloalto_fw"} 0
snmp_collection_duration_seconds_count{module="paloalto_fw"} 0
snmp_collection_duration_seconds{module="servertech_sentry3",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="servertech_sentry3",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="servertech_sentry3",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="servertech_sentry3"} 0
snmp_collection_duration_seconds_count{module="servertech_sentry3"} 0
# HELP snmp_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which snmp_exporter was built.
# TYPE snmp_exporter_build_info gauge
snmp_exporter_build_info{branch="master",goversion="go1.7.5",revision="6f8aa8a24d720b36991f29ffb179b2896e92090b",version="0.3.0"} 1
# HELP snmp_request_errors_total Errors in requests to the SNMP exporter
# TYPE snmp_request_errors_total counter
snmp_request_errors_total 0
# HELP snmp_unexpected_pdu_type_total Unexpected Go types in a PDU.
# TYPE snmp_unexpected_pdu_type_total counter
snmp_unexpected_pdu_type_total 0
````

**Comment by moepman** [comment]
Running the OIDs alone:
- `1.3.6.1.2.1.1.3` is fine.
- `1.3.6.1.2.1.2` is causing HTTP/500.
- `1.3.6.1.2.1.31.1.1` is causing HTTP/500.

**Comment by moepman** [comment]
````
$ snmpbulkget -v2c -c XXX switch1 1.3.6.1.2.1.2
IF-MIB::ifNumber.0 = INTEGER: 135
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifIndex.2 = INTEGER: 2
IF-MIB::ifIndex.3 = INTEGER: 3
IF-MIB::ifIndex.4 = INTEGER: 4
IF-MIB::ifIndex.5 = INTEGER: 5
IF-MIB::ifIndex.6 = INTEGER: 6
IF-MIB::ifIndex.7 = INTEGER: 7
IF-MIB::ifIndex.8 = INTEGER: 8
IF-MIB::ifIndex.9 = INTEGER: 9
$ snmpbulkget -v2c -c XXX switch1 1.3.6.1.2.1.1.3
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (145847484) 16 days, 21:07:54.84
SNMPv2-MIB::sysContact.0 = STRING: RZ
SNMPv2-MIB::sysName.0 = STRING: switch1
SNMPv2-MIB::sysLocation.0 = STRING: RZ
SNMPv2-MIB::sysServices.0 = INTEGER: 74
IF-MIB::ifNumber.0 = INTEGER: 135
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifIndex.2 = INTEGER: 2
IF-MIB::ifIndex.3 = INTEGER: 3
IF-MIB::ifIndex.4 = INTEGER: 4
$ snmpbulkget -v2c -c XXX switch1 1.3.6.1.2.1.31.1.1
IF-MIB::ifName.1 = STRING: A1
IF-MIB::ifName.2 = STRING: A2
IF-MIB::ifName.3 = STRING: A3
IF-MIB::ifName.4 = STRING: A4
IF-MIB::ifName.5 = STRING: A5
IF-MIB::ifName.6 = STRING: A6
IF-MIB::ifName.7 = STRING: A7
IF-MIB::ifName.8 = STRING: A8
IF-MIB::ifName.9 = STRING: A9
IF-MIB::ifName.10 = STRING: A10
````

**Comment by SuperQ** [comment]
Is that a truncated version?  The number of results doesn't match up.

**Comment by moepman** [comment]
That is what `snmpbulkget` returns, `snmpbulkwalk` returns a ton more.

**Comment by RichiH** [comment]
Also, please run without MIB resolution.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by SuperQ** [comment]
Please try this for comparison:

```
wget http://127.0.0.1:9116/snmp?target=switch1&module=default_ifindex
```

**Comment by moepman** [comment]
Running with default_ifindex works (having all three OIDs enabled and using the same auth credentials as with default).

Will post snmpbulkwalk in a bit.

**Comment by SuperQ** [comment]
That's what I thought.  There is likely some duplicated `ifDescr` strings that is causing the metrics handler to barf.  This is a bug.

Give this snmp.yml config a try, it should also work around the duplicate string problem:
https://github.com/SuperQ/tools/blob/master/snmp_exporter/default.yml

**Comment by SuperQ** [comment]
Oh, I think that config is not updated for blackbox_exporter 0.3.0.  I will have to update it.

**Comment by moepman** [comment]
Yes there are a few duplicate ifDescr and ifAlias entries, e.g. those:
````
.1.3.6.1.2.1.2.2.1.2.4800 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4801 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4802 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4803 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4804 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4805 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4806 = STRING: HP Switch software loopback interface
.1.3.6.1.2.1.2.2.1.2.4807 = STRING: HP Switch software loopback interface
````
(Can't post full output atm as it may contain VLAN names we don't want to leak)

**Comment by moepman** [comment]
@SuperQ your snmp.yml file seems to work fine, I also get proper Port Names in `http://prometheus:9090/consoles/snmp`

**Comment by SuperQ** [comment]
@brian-brazil There is still a bug here that there the exporter bombs out with a 500 error and nothing in the debug log.

**Comment by HammaBamma** [comment]
I too am experiencing this same issue.. I've even copied over known working snmp.yml files from other environments I work with, but this one server set here at this meeting does not want to respond. I get NAN on everything.. See below..


`# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 5.5162e-05
go_gc_duration_seconds{quantile="0.25"} 0.00011147
go_gc_duration_seconds{quantile="0.5"} 0.000156426
go_gc_duration_seconds{quantile="0.75"} 0.000249953
go_gc_duration_seconds{quantile="1"} 0.00645223
go_gc_duration_seconds_sum 0.031649157
go_gc_duration_seconds_count 102
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 10
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.8.3"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 2.391752e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 2.24032728e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.451835e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 332808
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 0.00019805569226590114
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 507904
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 2.391752e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 4.005888e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 3.629056e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 11311
# HELP go_memstats_heap_released_bytes Number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes gauge
go_memstats_heap_released_bytes 475136
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 7.634944e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.5068852419014359e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 2374
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 344119
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 4800
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 50312
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 65536
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.69016e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 1.241533e+06
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 753664
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 753664
# HELP go_memstats_sys_bytes Number of bytes obtained from system.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.16718e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 11
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 1
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.5077376e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.50688489341e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2.0156416e+07
# HELP snmp_collection_duration_seconds Duration of collections by the SNMP exporter
# TYPE snmp_collection_duration_seconds summary
snmp_collection_duration_seconds{module="arista_sw",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="arista_sw",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="arista_sw",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="arista_sw"} 0
snmp_collection_duration_seconds_count{module="arista_sw"} 0
snmp_collection_duration_seconds{module="cisco_wlc",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="cisco_wlc",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="cisco_wlc",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="cisco_wlc"} 0
snmp_collection_duration_seconds_count{module="cisco_wlc"} 0
snmp_collection_duration_seconds{module="default",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="default",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="default",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="default"} 0
snmp_collection_duration_seconds_count{module="default"} 0
snmp_collection_duration_seconds{module="default_ifindex",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="default_ifindex",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="default_ifindex",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="default_ifindex"} 0
snmp_collection_duration_seconds_count{module="default_ifindex"} 0
snmp_collection_duration_seconds{module="default_ifname",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="default_ifname",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="default_ifname",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="default_ifname"} 0
snmp_collection_duration_seconds_count{module="default_ifname"} 0
snmp_collection_duration_seconds{module="fortinet_fortigate",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="fortinet_fortigate",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="fortinet_fortigate",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="fortinet_fortigate"} 0
snmp_collection_duration_seconds_count{module="fortinet_fortigate"} 0
snmp_collection_duration_seconds{module="paloalto_fw",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="paloalto_fw",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="paloalto_fw",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="paloalto_fw"} 0
snmp_collection_duration_seconds_count{module="paloalto_fw"} 0
snmp_collection_duration_seconds{module="servertech_sentry3",quantile="0.5"} NaN
snmp_collection_duration_seconds{module="servertech_sentry3",quantile="0.9"} NaN
snmp_collection_duration_seconds{module="servertech_sentry3",quantile="0.99"} NaN
snmp_collection_duration_seconds_sum{module="servertech_sentry3"} 0
snmp_collection_duration_seconds_count{module="servertech_sentry3"} 0
# HELP snmp_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which snmp_exporter was built.
# TYPE snmp_exporter_build_info gauge
snmp_exporter_build_info{branch="HEAD",goversion="go1.8.3",revision="4388d6815791d6d616098f899110c9dca354028c",version="0.6.0"} 1
# HELP snmp_request_errors_total Errors in requests to the SNMP exporter
# TYPE snmp_request_errors_total counter
snmp_request_errors_total 0
# HELP snmp_unexpected_pdu_type_total Unexpected Go types in a PDU.
# TYPE snmp_unexpected_pdu_type_total counter
snmp_unexpected_pdu_type_total 0`

Tried it with Target vs. Address and same result..

**Comment by HammaBamma** [comment]
Sorry wrong again, /metric allows me to do a module and single address query and it works. but /metrics still returns NaN and the configuration information.

**Comment by dswarbrick** [comment]
Similarly, if the SNMP get / walk times out (e.g. because the target is dead / unreachable), snmp_exporter does not produce any valid metrics that could be ingested by Prometheus (and thus alerted on). For example, scraping a non-existent target IP results in:
> An error has occurred during metrics gathering:
>
> error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error getting target 192.0.2.1: Request timeout (after 3 retries)

This is (vaguely) human-friendly, but not Prometheus-friendly. I _presume_ that the `up` metric would be zero for this job, but I kinda expected something more like the blackbox_exporter approach with e.g. `probe_success` being zero.

**Comment by brian-brazil** [comment]
It would be 0, and this is Prometheus-friendly. There's no probe_success equivalent, as there's no useful metrics we can provide in this case - so why make extra work for the user by having them check an additional metric in addition to up?

**Comment by dswarbrick** [comment]
@brian-brazil Thanks for the quick response. The only counter argument I can come up with is whether it might be handy to have some distinction as to _why_ the scrape failed, available as a metric. For example, SNMP timeout, bad authn, invalid OID. If `up` is zero however, I guess we can work with that for now.

**Comment by SuperQ** [comment]
Sadly, most SNMP devices don't give a positive auth failure, so a network timeout is the same as a bad auth. Invalid OIDs similarly don't give any indication of a problem, they just return no data on a walk.

**Comment by brian-brazil** [comment]
I don't think there's anything for us to do here, so closing this old issue before it gets more sidetracked.
