### ISSUE TITLE
Support per device community

### ISSUE THREAD

**Issue by mweinelt** [prometheus/snmp_exporter#200]
We do treat communities like passwords and so every device has their own community, but communities are not configurable per device, only per group.

I'd propose accepting/overwriting the community string as part of the URLs GET Parameter, like:

http://localhost:9116/snmp?target=1.2.3.4&community=totallysecret

**Comment by brian-brazil** [comment]
You'll need to create a module per device for your setup then, or switch to the more usual setup where devices share communities.

URL parameters not considered secure with Prometheus, see https://prometheus.io/docs/operating/security/

**Comment by brointhemix** [comment]
Hello,

I actually agree with @mweinelt that per device or per logical group (nor per module) SNMP credentials setup would be a huge benefit. I have been working with multiple sizeable networks and one credential set for the whole network is relatively difficult to come by because policy, InfoSec guys, etc. etc. Recreating same module over and over for these and then updating them would be a great pain.

So I would like to reiterate @mweinelt 's request and ask for either a per device or a per logical group credentials setup option, favouring the per logical group one as it seems a more robust option.

Otherwise thanks for the great work!

**Comment by brian-brazil** [comment]
Logical groups are already covered by modules in the SNMP exporter, you'll need a module per credential. Configuration management should make this fairly easy, I presume you'd not be creating the config entirely by hand.

**Comment by brointhemix** [comment]
I agree that Prometheus's the general approach seems to be automated config (re)generation, so yes, I will have the config generation automated.

I just wanted to point out using my experience that network environments tend to be in different states of trying-to-but-not-enturely-attaining a single SNMP credential setup and that abstracting SNMP credentials configuration seemed to me a more streamlined approach than generating multiple modules holding the same complex configuration information and only differing by SNMP credentials setup.
