### ISSUE TITLE
Generate config file for Junos 12.3

### ISSUE THREAD

**Issue by Passpes** [prometheus/snmp_exporter#251]
### Host operating system: output of `uname -a`
16.04.1-Ubuntu SMP
### snmp_exporter version: output of `snmp_exporter -version`
snmp_exporter, version 0.8.0 

### What device/snmpwalk OID are you using?
SNMPv2-MIB::sysDescr.0 = STRING: Juniper Networks, Inc. ex2200-24t-4g Ethernet Switch, kernel JUNOS 12.3R9.4, Build date: 2015-02-12 11:18:43 UTC Copyright (c) 1996-2015 Juniper Networks, Inc.

### If this is a new device, please link to the MIB(s).
https://www.juniper.net/techpubs/software/junos/junos123/juniper-mibs-12.3R12.4.tgz

So now I extracted the juniper-mibs-12.3R12.4.tgz to $HOME/.snmp/mib as described in README but then when I try ./generator generate the snmp.yml file doesn't contain any module or configuration of Juniper MIB - is there anything I missed or how can I get an snmp.yml file for my Junos device?
 
![image](https://user-images.githubusercontent.com/6490137/33273724-743d67b4-d38e-11e7-8876-35cc05507d31.png)

**Comment by brian-brazil** [comment]
You need to add to the generator.yml too.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by Passpes** [comment]
Thx.
