### ISSUE TITLE
SNMP_Exporter Default port

### ISSUE THREAD

**Issue by nexusguy59** [prometheus/snmp_exporter#270]
Hello Guys,
I figured out how to run this on a different port rather than the default port, however I am getting an error:
<./snmp_exporter --web.listen-address=“:8082”
INFO[0000] Starting snmp exporter (version=0.9.0, branch=HEAD, revision=abb143a2b798ebb82167f407030056a00ead00ac)  source="main.go:125"
INFO[0000] Build context (go=go1.9.2, user=root@8246f0b1908c, date=20180226-16:10:54)  source="main.go:126"
INFO[0000] Listening on “:8082”                          source="main.go:205"
FATA[0000] listen tcp: address tcp/8082”: unknown port   source="main.go:206">

Can anyone point me in the right direction.

Thanks,

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by nexusguy59** [comment]
Ok I will do.that sorry
