### ISSUE TITLE
How Prometheus can be used for GitHub Enterprise monitoring?

### ISSUE THREAD

**Issue by vivuu1989** [prometheus/snmp_exporter#418]
Hello Experts,

We Have our own GitHub Enterprise which is installed as an appliance and are looking for 2 things and how Prometheus can help here with these requirements.

We need to have a central single monitoring solution which should monitor our GitHub Enterprise application. Currently we are using different different applications for monitoring the load, CPU, disk usage other application specific things. GHE will support SNMP and collectd forwarding .. whether Prometheus will support ?

We need to have a central log system. which will analyze the logs. GitHub appliance will supports syslog-style log streams is supported, So whether we can make Prometheus for the same… ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by mvbakker** [comment]
@vivuu1989 Would you mind sharing if you solved it and if so, how did you do it? I am facing a similar challenge :)
