### ISSUE TITLE
scraping target timeout

### ISSUE THREAD

**Issue by Reob** [prometheus/snmp_exporter#419]
msg="Error scraping target x.x.x.x: error getting target x.x.x.x: Request timeout (after 3 retries)" source="collector.go:211"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
