### ISSUE TITLE
FR - Specify Community and Version in Scrape config

### ISSUE THREAD

**Issue by rhys-evans** [prometheus/snmp_exporter#444]
Basically being able to pass the community and version as part of the scrape config would be useful.

Please see (shamelessly linked to)  https://raw.githubusercontent.com/ConSol/omd/labs/packages/prometheus_snmp_exporter/patches/0001-community-and-version-can-be-passed-by-get-param.patch

Thanks

**Comment by brian-brazil** [comment]
This purposefully isn't possible, if you need different configuration you can have different modules. In addition it's insecure to pass secrets as URL parameters.

**Comment by yuyutime** [comment]
`Community per module` approach is a partial solution since snmp_exporter doesn't support multiple modules in one prometheus job and forces to use job per module in scrape config.

Also it is hardly applicable in case of network with unique community per device design.
snmp_exporter's config section wtih  `target -> auth_attributes` dictionary won't require to pass secrets over network.

**Comment by SuperQ** [comment]
> support multiple modules in one prometheus job

This is incorrect. It's perfectly possible to support multiple modules per job via relabeling.
