### ISSUE TITLE
Multiple communities in prometheus.yml

### ISSUE THREAD

**Issue by freedomwarrior** [prometheus/snmp_exporter#463]
Hello.
Is it possible to set different community strings for each target in prometheus.yml?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
