### ISSUE TITLE
When I execute the "make mibs" prompt Make: *** [mibs/KEEPALIVED-MIB] Error 7

### ISSUE THREAD

**Issue by happinesslijian** [prometheus/snmp_exporter#464]
When I execute the "make mibs" prompt
Make: *** [mibs/KEEPALIVED-MIB] Error 7
help me！

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
