### ISSUE TITLE
Can not collect metric on Cisco Devices

### ISSUE THREAD

**Issue by hieuit1506** [prometheus/snmp_exporter#470]
Dear Admin,

I have a problem when I collect a metric on Cisco devices. 

**An error has occurred during metrics gathering:
error collecting metric Desc{fqName: "snmp_error", help: "Error scraping target", constLabels: {}, variableLabels: []}: error walking target 10.10.10.101: Request timeout (after 3 retries)**

Although I can check with snmpwalk. It's very fast.

Please help me fix bug.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
