### ISSUE TITLE
Cannot find the ifHCInOctets in snmp_exporter

### ISSUE THREAD

**Issue by wiljay** [prometheus/snmp_exporter#479]
Hi team,

I recently checked the data collected by prometheus and found that ifHCInOctets is missing,but snmp config and snmp yml can find the ifHCInOctets OID.My SNMP_EXPORTER version is 0.018.1.
![config](https://user-images.githubusercontent.com/42308868/74332125-10495880-4dd0-11ea-829f-d643ff22eade.png)
![cannot find](https://user-images.githubusercontent.com/42308868/74332138-14757600-4dd0-11ea-83a6-9a5d1162a0d9.png)

Thanks
JACK

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
