### ISSUE TITLE
[BUG]   context deadline exceeded !!! no timeout set

### ISSUE THREAD

**Issue by tqangxl** [prometheus/snmp_exporter#491]
prometheus 2.16
snmp_exporter 0.17.0

![image](https://user-images.githubusercontent.com/9669944/76697039-0b2c4180-66cd-11ea-8fae-62b072477acd.png)

![image](https://user-images.githubusercontent.com/9669944/76697056-2bf49700-66cd-11ea-8460-e5b80519a316.png)

![image](https://user-images.githubusercontent.com/9669944/76697074-5cd4cc00-66cd-11ea-901b-3b27481fc484.png)

![image](https://user-images.githubusercontent.com/9669944/76697099-9d344a00-66cd-11ea-8c29-ea1df0ff52b3.png)

**Comment by tqangxl** [comment]
due to snmp_exporter memery limited?
how to change

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
