### ISSUE TITLE
SNMP_exporter for CYBEROAM

### ISSUE THREAD

**Issue by yesminek** [prometheus/snmp_exporter#495]
Hi , 
i am working with a cyberoam Firewall , while running snmpwalk he gives directly MIBs so i think there is no need to create generator.yml , 
Can you help me in finding where is the issue? My SNMP exporter cannot collect SNMP data from cyberoam firewall , 
steps : i installed snmp_exporter and snmpwalk works correctly but i don't know what i can change ? 

Thanks .

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
