### ISSUE TITLE
Prometheus redirects snmp url to one that appends %3A9116 at the end of the url. My prometheus.yml file has this relabel configuration:

### ISSUE THREAD

**Issue by hamedg1** [prometheus/snmp_exporter#498]

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
