### ISSUE TITLE
Prometheus target url for snmp loads extra %3A9116 on the end of the url.

### ISSUE THREAD

**Issue by hamedg1** [prometheus/snmp_exporter#499]
### Host operating system: output of `uname -a`

GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

0.17.0
### What did you expect to see?
http://10.2xx.x.x:9116/snmp?module=if_mib&target=10.146.x.x

### What did you see instead?
http://10.2xx.x.x:9116/snmp?module=if_mib&target=10.146.x.x%3A9116

**Comment by hamedg1** [comment]
When clicking on Prometheus snmp target to view its metrics page, Prometheus loads snmp url to one that appends %3A9116 at the end of the url. Any idea on how to remove this. Does it involve relabel config? My prometheus.yml file has this relabel configuration:   - job_name: 'snmp_exporter'     scrape_interval: 30s     file_sd_configs:     - files:       - 'snmp_targets.json'     metrics_path: /snmp     params:       module: [if_mib]     relabel_configs:       - source_labels: [__address__]         target_label: __param_target       - source_labels: [__param_target]         target_label: instance       - target_label: __address__         replacement: 10.2xx.x.x:9116  # The SNMP exporter's real hostname:port.

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
