### ISSUE TITLE
Prom config error

### ISSUE THREAD

**Issue by dmytroshokha** [prometheus/snmp_exporter#510]
Hello! I use prometheus with my "standard" configuration. If I add your config as in the example to my prometheus, then the config will not load. How to fix this problem?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
