### ISSUE TITLE
Dashboard: abnormal display of quantity

### ISSUE THREAD

**Issue by dmytroshokha** [prometheus/snmp_exporter#512]
How to achieve optimal display of load values ​​using SNMP Interface Throughput dashboard? I tried changing the format, but the display became abnormal.
![1](https://user-images.githubusercontent.com/62596085/80494268-28605b00-896f-11ea-8319-8b3c0590c82e.GIF)
![2](https://user-images.githubusercontent.com/62596085/80494278-29918800-896f-11ea-9a2c-3d20c397d1b3.GIF)
![3](https://user-images.githubusercontent.com/62596085/80494280-2a2a1e80-896f-11ea-8fb0-1a015e560dc8.GIF)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
