### ISSUE TITLE
Ignore certs when using hostnames

### ISSUE THREAD

**Issue by spoer78** [prometheus/snmp_exporter#517]
Hi there,

when we are using the SNMP exporter with the IP addresses of the target, the scraping is done in about 700ms, when we use the FQDN/hostname for the target, its taking about 11s. Is this because he is doing a certificate check when using a hostname and due to a self signed cert on the Dell IDRAC side, it has a 10s timeout? I tried the following in the prometheus config:

      tls_config:
        insecure_skip_verify: false

... but it had no effect.

Is there a way to configure snmp-exporter itself to skip the certificate check (if thats indeed the issue)?

Thanks and best regards,
sp

**Comment by SuperQ** [comment]
SNMP doesn't use TLS. This sounds more like a DNS lookup timeout problem.

**Comment by brian-brazil** [comment]
Yeah, this sounds like a Prometheus support question so closing. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
