### ISSUE TITLE
server returned HTTP status 400 Bad Request

### ISSUE THREAD

**Issue by rmvalliappan** [prometheus/snmp_exporter#521]
Hi 
Trying to monitor fortigate Firewall 
Getting this error -server returned HTTP status 400 Bad Request 
Trying based on this 
https://grafana.com/grafana/dashboards/7567

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by rmvalliappan** [comment]
Thanks
