### ISSUE TITLE
Get http://127.0.0.1:9116/snmp?module=if_mib&target=X.X.X.X: context deadline exceeded

### ISSUE THREAD

**Issue by dadapapapa** [prometheus/snmp_exporter#526]
Please help. we have a problem. When snmp_exporter is used to grab stack switches, it displays (Get http://127.0.0.1:9116/snmp?module=if_mib&target=X.X.X.X: context deadline exceeded).
There is no problem with a separate switch.
![SNMP](https://user-images.githubusercontent.com/63433429/83087751-990cab80-a0c4-11ea-9e0c-6df7b24bb4d8.png)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
