### ISSUE TITLE
How to do simple math on values

### ISSUE THREAD

**Issue by audunmg** [prometheus/snmp_exporter#542]
A lot of our devices have values like 1.1 and 13.5 represented as 11 and 135 in snmp, and it seems quite common.

Is there a simple way to export the "correct" numbers?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
