### ISSUE TITLE
SNMP_Exporter connect: connection refused

### ISSUE THREAD

**Issue by vmayrink1** [prometheus/snmp_exporter#546]
Hello, I'm new here, can you help me?
I'm having this error on prometheus.yml when trying to connect to my snmp_exporter container.
Thank you.

![image](https://user-images.githubusercontent.com/35264079/86683639-1edf1900-bfd8-11ea-9a47-a1072a54d696.png)
![image](https://user-images.githubusercontent.com/35264079/86683841-577ef280-bfd8-11ea-8a74-9a1e6f257513.png)
![image](https://user-images.githubusercontent.com/35264079/86684055-901ecc00-bfd8-11ea-8fce-c304c80dee91.png)
![image](https://user-images.githubusercontent.com/35264079/86684320-d116e080-bfd8-11ea-9c15-7429226254ee.png)

**Comment by brian-brazil** [comment]
That's a networking problem getting to the node exporter. 
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
