### ISSUE TITLE
snmp_exporter error collectorgo:224 module and msg="error scrapting target" err="scrape canceled (possible time out) walking target x.x.x.x" 

### ISSUE THREAD

**Issue by se7en102** [prometheus/snmp_exporter#554]
I have issue with monitoring firewall fortigate 101E.
I setup prometheus and grafana , snmp_exporter on centos 7 to monitoring firewall fortigate 101E.
when i access http://ip-prometheus-server:9116/target=ip-fortigate?module=fg-snmp , it take long time , about 5 minut to get backup information. 
when i run systemctl status snmp_exporter -l  -> it have error as below: 
snmp_exporter error collectorgo:224 module and msg="error scrapting target" err="scrape canceled (possible time out) walking target x.x.x.x" 

fortigate log  report have get snmp traffic from prometheus server and it accepted, it can download data from fortigate.

How can i process to fix it in this case ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
