### ISSUE TITLE
How can convert Hex string to String ? 

### ISSUE THREAD

**Issue by se7en102** [prometheus/snmp_exporter#558]
I have monitoring Aruba Temperature 
snmpwalk with OID can be see Temperature Min | Max | Current , but snmp_exporter only show Current temperature. Min & Max is Hexa number 0x323243
hpSystemAirMinTemp{hpSystemAirMinTemp="0x323243",hpSystemAirSensor="0"} 1
When convert it "0x323243" to string "22C" 
that is information i want to display in grafana.
So, how can i convert hex to string ini this case ? 
![temperature aruba OID](https://user-images.githubusercontent.com/56648095/91270750-592c9180-e7a3-11ea-8c21-e1ada5647079.jpg)
![snmp_exporter temperature aruba switch](https://user-images.githubusercontent.com/56648095/91270772-60539f80-e7a3-11ea-995d-914a253382dd.jpg)
![2020-08-26_8-18-37](https://user-images.githubusercontent.com/56648095/91270780-62b5f980-e7a3-11ea-88ad-b5a14ea15470.jpg)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by shitingting521** [comment]
so I have same problem ,how to sovle it
