### ISSUE TITLE
Building docker container locally

### ISSUE THREAD

**Issue by clienthax** [prometheus/snmp_exporter#564]
### Host operating system: output of `uname -a` 
Linux 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### snmp_exporter version: output of `snmp_exporter -version`

version=0.19.0, branch=master, revision=8cf95a123f8921f378bb713e6ed1ef242363869d

### What did you do that produced an error?
make docker
### What did you expect to see?
A completed build
### What did you see instead?
```
Step 7/11 : COPY .build/${OS}-${ARCH}/snmp_exporter  /bin/snmp_exporter
COPY failed: stat /var/lib/docker/tmp/docker-builder453370970/.build/linux-amd64/snmp_exporter: no such file or directory
Makefile.common:237: recipe for target 'common-docker-amd64' failed
make: *** [common-docker-amd64] Error 1
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
