### ISSUE TITLE
Lookup add EnumValues 

### ISSUE THREAD

**Issue by zhujintao** [prometheus/snmp_exporter#587]
- name: chassisStatus
    oid:  1.3.6.1.4.1.674.10892.5.4.300.70.1.5.1
    type: EnumAsStateSet
    indexes:
    - labelname: chassis
      type: EnumAsInfo
      enum_values:
       0: ok
       1: yes
    lookups:
    - labels:
      - chassis
      labelname: Reading
      oid: 1.3.6.1.4.1.674.10892.5.4.300.70.1.6.1
      type: gauge
      enum_values:
        0: ok
        1: no
    enum_values:
      0: ok
      1: no

level=error ts=2020-12-08T01:01:37.415Z caller=main.go:156 msg="Error parsing config file" err="yaml: unmarshal errors:\n  line 46: field enum_values not found in type config.Lookup"

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
