### ISSUE TITLE
sample file configuration for multi snmp cisco switch with prometheus snmp_exporter

### ISSUE THREAD

**Issue by zeinab71421** [prometheus/snmp_exporter#588]
Hi all, now i am planning to monitor all cisco switch (6509,4506,2960s ...) of my current company . 

i could monitor mikrotik with generator.yml and snmp.yml but for cisco switch i cant and give me error timeout for scrapping.

i use psometheus 2.23
gol.15
snmp_exporter 19

could you please give me sample configure such as :
generation.yml
prometheus.yml
prometheus.service 
snmp.yml 

all files are configured for 2 or more switch .
Thanks !

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by zeinab71421** [comment]
Thanks !
I asked there.But If you know, please help me to fix it
