### ISSUE TITLE
make: *** [Makefile:161：mibs/KEEPALIVED-MIB] 错误 35

### ISSUE THREAD

**Issue by renziyou** [prometheus/snmp_exporter#590]
make mibs
****
![image](https://user-images.githubusercontent.com/8150303/101971653-030a2e00-3c6e-11eb-8d1e-e88c8a48342a.png)

已删除'/tmp/tmp.AIvbPGiRLF'
>> Downloading IANA charset MIB
>> Downloading IANA ifType MIB
>> Downloading IANA printer MIB
>> Downloading KEEPALIVED-MIB
make: *** [Makefile:161：mibs/KEEPALIVED-MIB] 错误 35
[root@prometheus generator]# uname -a
Linux prometheus 5.9.9-1.el8.elrepo.x86_64 #1 SMP Tue Nov 17 19:01:48 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@prometheus generator]# cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
