### ISSUE TITLE
HP SERVER HARDWARE ALERT

### ISSUE THREAD

**Issue by zrcorsica** [prometheus/snmp_exporter#591]
Hi,

please I would like to monitor hardware of HP SERVER (ProLiant DL360 g10/g8/g7/g6) hosting Vmware esxi 6.7 OS and centos 7 OS.

Thus I would like to monitor via snmp vmware OS / Centos OS. Is there someone who has already done the alert file for this purpose ? I am searching OID to monitor disk faiilure, memory failure, system board failure, network interface failure, smart array failure...

thank you a lot

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
