### ISSUE TITLE
how to set password in version 2 in snmp exporter

### ISSUE THREAD

**Issue by rezabojnordi** [prometheus/snmp_exporter#593]
### Host operating system: output of `uname -a`
Linux metric_monitoring 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### snmp_exporter version: output of `snmp_exporter -version`

snmp_exporter-0.19.0

### What device/snmpwalk OID are you using?
vm linux ubuntu 18.04 and siwtch cisco 494810ge

### What did you do that produced an error?
level=info ts=2020-12-27T10:55:31.858Z caller=collector.go:224 module=if_mib target=172.16.108.10 msg="Error scraping target" err="scrape canceled (possible timeout) getting target 172.16.108.10"

### What did you expect to see?
metrics switch cisco
### What did you see instead?

I set the password on the Cisco switch with version 2 of the snmp, but I could not get data with the exporter snmp how to set just password in snmp exporter for version2

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
