### ISSUE TITLE
Support `auth` alongside target & module as distinct property

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#619]
auth is orthogonal from the target, the data model and from what data to receive. As such, it will be split out into its own section.

For backwards compatibility, inline auth should be supported, but the new pattern encouraged.

Open questions:
* Should we allow auth to live in a secondary file to completely detach global OID etc configuration from user-specific config?
* Should we offer inline-line loading of files or explicitly have a few distinct files? Inline seems better.
* Should we offer a baseline UI to show which files are loaded?
* Should the exporter emit information like files loaded in `_info` or through a gauge?

As this touches a lot of questions in https://github.com/prometheus/snmp_exporter/issues/85 CC @glensc

**Comment by RichiH** [comment]
https://docs.google.com/document/d/1McJJIiJfHgoecVrVNXx4ABJmI5M21e-6O9IgMNbVnvw

**Comment by RichiH** [comment]
After more thought:
> Should we allow auth to live in a secondary file to completely detach global OID etc configuration from user-specific config?
https://github.com/prometheus/snmp_exporter/issues/85 will take care of this and people can structure it as they wish.

The new default config we provide should most likely break it out.

> Should we offer inline-line loading of files or explicitly have a few distinct files? Inline seems better.

I flipped. Let's make it explicit on CLI. Directory support takes away the need for inlinig, IMO. As such, we should offer fewer ways to do the same thing to avoid long-term confusion.

> Should we offer a baseline UI to show which files are loaded?

I think we must.

> Should the exporter emit information like files loaded in _info or through a gauge?

I think we should. Unclear if we should do
* one `_info`, lots of labels
* one `_info`, overload a single label
* one metric per file

New open question: Does that mean we're listing the directory name, what is found and activated inside, or both of those?

**Comment by xkilian** [comment]
What you are describing should be handled in logging at exporter startup, and in the web UI. It is not meant for info metrics IMO.

**Comment by pobk** [comment]
A secondary authentication file that can be linked to targets using the similar mechanism to module would be appreciated here. That way, we're not passing credentials in the clear, and admins have the choice of implementing common credentials, or device specific credentials.

The way I see this working is where we would normally use `?module=<mib>` we would add `credentials=<creds>`

**Comment by pobk** [comment]
My 2 pence:

1. Credentials should be stored separately from the MIB definitions. Having a file which contains credentials separate from the snmp config would allow a greater flexibility around securing that file.
2. Allowing the exporter to be targeted using `credentials=` as well as `module=` would allow for some flexibility in targeting.

My employer uses LastPass, and we've integrated that into an ansible workflow. This gives greater protection to our systems estate since if you don't have access to the credentials from the credentials store you cannot access the system to run any of the playbooks. This is something that could easily be implemented in other ways too.

This also works for generating files full of credentials where each node has separate credentials configured.

**Comment by candlerb** [comment]
This is great!

I would find it extremely useful if you were able to load multiple config files:

```
--config.dir=/etc/snmp_exporter/modules.d --config.dir=/etc/snmp_exporter/auths.d
# OR
--config.file='/etc/snmp_exporter/modules.d/*.yml' --config.file='/etc/snmp_exporter/auths.d/*.yml'
```

This would allow you to drop in pre-compiled modules without having to merge YAML files (which unfortunately isn't a simple concatenation). [exporter_exporter](https://github.com/QubitProducts/exporter_exporter#directory-based-configuration) provides this feature. (Would be nice for blackbox_exporter too)

Since in the current design a single YAML file has both "auths" and "modules" keys, it would then be up to the user whether they want to have combined module+auth files, or separate files in the same directory, or separate directories.

I have a couple of other questions relating to the current PR in #859 and backwards compatibility.

Firstly, it's not clear to me whether existing snmp.yml files with auth-per-module will still work:

```
auths:
  ...
modules:
  foo:
    auth: # is a legacy 'auth' section allowed here?
      ...
```

If not, or we want a clean break, it would be very easy to write a conversion tool which converts snmp.yml into the new form, providing an "auth" named the same as each original "module":

```
# output from tool
auths:
  foo:
    ...
modules:
  foo:
    ...
```

Then a scrape which supplies `module` but not `auth` could implicitly look for an `auth` with the same name (falling back to "public_v2" if that doesn't exist).

Another possibility would be to stick with the existing file format, but allow users to create modules which have only auth, only SNMP, or both:

```
modules:
  foo:
    walk:
      ...
    get:
      ...
  bar:
    auth:
      ...
  baz:
    auth:
      ...
```

Then you could do:

```
/snmp?module=foo&auth=bar    # use the 'foo' module but the 'auth' creds from bar
/snmp?module=foo&auth=baz    # use the 'foo' module but the 'auth' creds from baz
/snmp?module=foo             # use the 'foo' module with 'auth' creds under foo (if any): legacy mode
```

However, I think in the long run the top-level separation is cleaner.

**Comment by candlerb** [comment]
I'm guessing that legacy files will still work?

```
modules:
  foo:
    auth: # is a legacy 'auth' section allowed here?
      ...
```

If not, or we want a clean break, it would be very easy to write a conversion tool which converts snmp.yml into the new form, providing an "auth" named the same as each original "module":

```
# output from tool
auths:
  foo:
    ...
modules:
  foo:
    ...
```

Then a scrape which supplies `module` but not `auth` could implicitly look for an `auth` with the same name (falling back to "public_v2" if that doesn't exist).

Another possibility would be to stick with the existing file format, but allow users to create modules which have only auth, only SNMP, or both:

```
modules:
  foo:
    walk:
      ...
    get:
      ...
  bar:
    auth:
      ...
  baz:
    auth:
      ...
```

Then you could do:

```
/snmp?module=foo&auth=bar    # use the 'foo' module but the 'auth' creds from bar
/snmp?module=foo&auth=baz    # use the 'foo' module but the 'auth' creds from baz
/snmp?module=foo             # use the 'foo' module with 'auth' creds under foo (if any): legacy mode
```

However, I think in the long run the top-level separation is cleaner.
