### ISSUE TITLE
Should we allow multiple modules per target?

### ISSUE THREAD

**Issue by RichiH** [prometheus/snmp_exporter#620]
This is an ongoing discussion between @SuperQ and I; input very much appreciated.

Pro:
* Less config bloat
* Allows for modular configs, which might be nice for modular chassis and such

Con:
* Non-obvious precedence, merging, etc
* Harder to debug

Neutral:
* Through https://github.com/prometheus/snmp_exporter/issues/619 and others, we may be able to reduce pressure on snmp.yml to be touched at all, thus reducing the need for any human to ever touch snmp.yml

Currently, @SuperQ is slightly in favor, I am slightly against, but could easily change. I am, however, strongly in favor of doing this later rather than sooner due to reduced pressure on snmp.yml.

**Comment by xkilian** [comment]
Pro:

- Less config bloat for configurations that handle multiple versions of the same device: (ex. 24 port switch monitor only uplinks, 24 port switch monitor all ports, 24 port switch monitor all ports named "MON.*", etc.

Con:

- Must not introduce config complexity in prometheus.yml and its dependant targets.json files (ex. Due to having to provide a list of modules or other funky stuff)
- Code needs to handle some way to order the modules

Implementation:

I would see an implementation that uses import module statements in the device module. The order of imports would impart the ordering logic. Doing it this way should not make it overly complexe to troubleshoot. As the the generator would essentially build an intermediate module with all the sections ordered by the import order. I hope this makes sense.

**Comment by tardoe** [comment]
I like this idea, it reduces the manual config work and lets the generator do the heavy lifting. While I agree merging and such does become a pain but at the same time, a dumb merging strategy (no de-dup etc.) would mean the onus is on the user to ensure their generator input is sane.

It would be so much easier to be able to define e.g.:

```
metrics:
	ifmib:
	  table: <oid>
    ifbgp4:
      table: <oid>
module:
    juniper_switch:
		metrics:
			- ifmib
	juniper_router:
		metrics: 
			- ifmib
			- ifbgp4
```
    
https://github.com/toni-moreno/snmpcollector actually does a very good job of defining SNMP objects and tables into metrics like this and allow you to collect them into "metric groups" for defining to devices.

**Comment by ikroumov** [comment]
Allowing multiple modules will be beneficial for the people to minimize level of effort and clear confusion

**Comment by shulianwang** [comment]
Hopefully, this feature will be implemented as soon as possible, because it really makes configuration work much easier!!!

**Comment by SuperQ** [comment]
This is now supported. https://github.com/prometheus/snmp_exporter/pull/945
