### ISSUE TITLE
Could use separate timeout setting and/or retry logic for DNS lookups

### ISSUE THREAD

**Issue by tnn2** [prometheus/snmp_exporter#941]
I have these settings in my snmp.yml:
```
  retries: 10
  timeout: 300ms
  max_repetitions: 32
```
Occasionally I get this error  in the log and the scrape fails:
```
ts=2023-08-10T08:01:10.023Z caller=main.go:106 \
  level=debug module=if_mib \
  target=some-core-router.myorg \
  msg="Starting scrape"
ts=2023-08-10T08:01:10.323Z caller=collector.go:390 \
  level=info module=if_mib \
  target=some-core-router.myorg \
  msg="Error scraping target" err="error connecting to target some-core-router.myorg: error establishing connection to host: dial udp: lookup some-core-router.myorg: i/o timeout"
```

The issue seems to be that sometimes the organization's DNS server is a bit slow to respond and can take up to 1200ms. 

Apparently the SNMP timeout setting also (perhaps unintentionally?) affects DNS lookups. But the retry setting does not seem to affect DNS lookups so the whole ScrapeTarget aborts after 300ms. It would be nice to be able to configure this separately so please consider this feature request to either have a separate timeout setting or add a retry loop for DNS timeouts.

**Comment by tnn2** [comment]
[retry_dns_errors.patch](https://github.com/prometheus/snmp_exporter/files/12314532/retry_dns_errors.patch)
This patch solves the problem for me. Maybe there's some better way to do it.

**Comment by dswarbrick** [comment]
The `retries` and `timeout` settings in the SNMP modules configuration are simply passed to the [GoSNMP](https://pkg.go.dev/github.com/gosnmp/gosnmp#GoSNMP) handle. A Go `context` is also passed to it.

In this situation, `retries` has nothing to do with DNS resolution, and is merely the number of times that an SNMP request will be resent if the remote does not respond.

GoSNMP uses a totally standard `net.ResolveUDPAddr` to resolve the address of the target _before_ sending any actual SNMP traffic to it, so the `timeout` should have no bearing here either. GoSNMP uses the `timeout` in its `net.Dialer` (i.e., for socket connect timeout, if using TCP), and to set an IO deadline on the reading of SNMP responses.

The default timeout used by GoSNMP is two seconds, and the default used by snmp_exporter is five seconds. Is there some reason why you have lowered this substantially?

Also, since your DNS server seems generally quite slow, have you considered running a local DNS cache on the snmp_exporter host, such as systemd-resolved, dnsmasq, NodeLocal DNSCache etc?

**Comment by tnn2** [comment]
> The default timeout used by GoSNMP is two seconds, and the default used by snmp_exporter is five seconds. Is there some reason why you have lowered this substantially?

Yes, packet loss. I agree the network should be fixed instead but it was unexpected application behavior to see DNS resolution start failing with a lower SNMP timeout setting. As you can see from the pasted log the connect does fail exactly after 300ms. Since this seems be an issue with GoSNMP rather than snmp_exporter I'll go ahead and close the issue and ask to have a caching resolver installed locally. Thanks.

**Comment by SuperQ** [comment]
If you want to make improvements in upstream GoSNMP, I'm happy to review those. I'm a maintainer there as well.
